In [12]:
import numpy as np

In [13]:
C = np.array([
    [1.0, 0.8, 0.6],
    [0.8, 1.0, 0.4],
    [0.6, 0.4, 1.0]])

In [14]:
# diagonalise
eigvals, P = np.linalg.eigh(C)
eigvals, P = eigvals[::-1], P[:, ::-1]
D = np.diag(eigvals)

In [15]:
P.round(2)

array([[-0.63, -0.15, -0.76],
       [-0.58, -0.54,  0.6 ],
       [-0.51,  0.82,  0.26]])

In [16]:
P.T.round(2)

array([[-0.63, -0.58, -0.51],
       [-0.15, -0.54,  0.82],
       [-0.76,  0.6 ,  0.26]])

In [17]:
D.round(2)

array([[2.21, 0.  , 0.  ],
       [0.  , 0.62, 0.  ],
       [0.  , 0.  , 0.16]])

In [18]:
C = P @ D @ P.T
C

array([[1. , 0.8, 0.6],
       [0.8, 1. , 0.4],
       [0.6, 0.4, 1. ]])

In [19]:
# reconstruct C from eigvals x outer product of eigenvectors  

u1 = P[:,0][:, np.newaxis]
u2 = P[:,1][:, np.newaxis]
u3 = P[:,2][:, np.newaxis]

B =eigvals[0]*u1@u1.T \
+ eigvals[1]*u2@u2.T \
+ eigvals[2]*u3@u3.T
B

array([[1. , 0.8, 0.6],
       [0.8, 1. , 0.4],
       [0.6, 0.4, 1. ]])

In [20]:
# compute cutoff point

N = 3
T = 20
Q = T/N
q = 1/Q
print('q=', q)

cutoff = (1+np.sqrt(q))**2

print('eigval1=', eigvals[0].round(4))
print('cutoff=', cutoff.round(4))

q= 0.15
eigval1= 2.2149
cutoff= 1.9246


In [21]:
def clip_eigvals(eigvals, cutoff):
    clipped_eigvals = eigvals.copy()
    mask = eigvals < cutoff  # boolean mask for eigvals below cutoff
    n_below_cutoff = np.sum(mask)  # count number of eigvals below cutoff
    k = np.sum(eigvals[mask]) / np.sum(mask) # compute k so that tr(C)=tr(C')=N
    print('k=', np.round(k, 4))
    clipped_eigvals[mask] = k  # replace eigvals below cutoff with k
    return clipped_eigvals
eigvals_clipped = clip_eigvals(eigvals, cutoff)

k= 0.3925


In [22]:
D_clean = np.diag(eigvals_clipped)
D_clean.round(4)

array([[2.2149, 0.    , 0.    ],
       [0.    , 0.3925, 0.    ],
       [0.    , 0.    , 0.3925]])